import { NextResponse } from "next/server"

export async function GET() {
  const alerts = [
    {
      id: 1,
      type: "security",
      severity: "Crítico",
      title: "Ataque DDoS detectado",
      message: "Flood detectado en dispositivo 192.168.1.45 - Tráfico anómalo de 500+ paquetes/seg",
      timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
      device: "192.168.1.45",
      protocol: "MQTT",
      resolved: false,
      details:
        "Se detectó un patrón de tráfico anómalo con más de 500 paquetes por segundo desde múltiples fuentes. El dispositivo puede estar bajo ataque DDoS.",
    },
    {
      id: 2,
      type: "security",
      severity: "Crítico",
      title: "Man-in-the-Middle detectado",
      message: "Posible ataque MITM en comunicación CoAP entre 192.168.1.46 y gateway",
      timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      device: "192.168.1.46",
      protocol: "CoAP",
      resolved: false,
      details:
        "Se detectaron certificados SSL/TLS sospechosos en la comunicación. Los paquetes pueden estar siendo interceptados.",
    },
    {
      id: 3,
      type: "security",
      severity: "Medio",
      title: "Acceso no autorizado",
      message: "Intento de acceso no autorizado desde 10.0.0.23 al dispositivo PLC",
      timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      device: "192.168.1.47",
      protocol: "Modbus",
      resolved: false,
      details: "Se detectaron múltiples intentos de autenticación fallidos desde una IP externa no autorizada.",
    },
    {
      id: 4,
      type: "device",
      severity: "Bajo",
      title: "Nuevo dispositivo conectado",
      message: "Dispositivo IoT desconocido conectado a la red - MAC: 00:1B:44:11:3A:C5",
      timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
      device: "192.168.1.49",
      protocol: "MQTT",
      resolved: true,
      details: "Un nuevo sensor de temperatura se conectó a la red y fue autorizado automáticamente.",
    },
    {
      id: 5,
      type: "network",
      severity: "Medio",
      title: "Latencia elevada detectada",
      message: "Latencia anormalmente alta en comunicaciones MQTT (>500ms)",
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      device: "192.168.1.45",
      protocol: "MQTT",
      resolved: false,
      details:
        "La latencia promedio ha aumentado significativamente, posible congestión de red o problema de conectividad.",
    },
    {
      id: 6,
      type: "system",
      severity: "Bajo",
      title: "Actualización de firmware disponible",
      message: "Nueva versión de firmware disponible para dispositivos CoAP",
      timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      device: "192.168.1.46",
      protocol: "CoAP",
      resolved: false,
      details: "Firmware v2.1.3 disponible con mejoras de seguridad y corrección de vulnerabilidades.",
    },
    {
      id: 7,
      type: "security",
      severity: "Crítico",
      title: "Vulnerabilidad crítica detectada",
      message: "CVE-2024-0001 detectada en dispositivo Modbus - Requiere acción inmediata",
      timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      device: "192.168.1.47",
      protocol: "Modbus",
      resolved: true,
      details: "Vulnerabilidad de ejecución remota de código parcheada exitosamente.",
    },
    {
      id: 8,
      type: "network",
      severity: "Medio",
      title: "Pérdida de paquetes detectada",
      message: "Pérdida de paquetes del 15% en comunicaciones HTTP",
      timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      device: "192.168.1.48",
      protocol: "HTTP",
      resolved: false,
      details: "Alta pérdida de paquetes puede indicar problemas de conectividad o interferencia.",
    },
  ]

  return NextResponse.json(alerts)
}
